---
title: "PS270 Final Project"
author: "Isabelle Seiler"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project Proposal 

My research question is: How did race relate to voting behavior in the 2024 presidential election? For my final project, I will use the American National Election Studies (ANES) 2024 Time Series Study to examine how racial identity correlates with presidential vote choice.

My hypothesis is that racial identity was significantly associated with vote choice in 2024. Specifically, my research measure whether Black voters were more likely to support the Democratic candidate, while White voters were more likely to support the Republican candidate. This hypothesis is plausible because voters tend to shape their political preferences based on their social identities. Racial identity can be predict voting behavior in U.S. presidential elections, and it likely played a role in the 2024 election.

My main independent variable is respondent race. In the ANES 2024 study, race is measured as a categorical variable that identifies respondents as White, Black, Hispanic, Asian, or other racial groups. This variation across respondents allows me to examine whether differences in racial identity are systematically related to vote choice.

The dependent variable is presidential vote choice in 2024 between the two major-party candidates. I will code this variable so that 1 represents a vote for the Democratic candidate and 0 represents a vote for the Republican candidate, excluding respondents who did not vote for a major-party candidate.

Evidence supporting my hypothesis would be a statistically significant relationship between race and vote choice, such that certain racial groups were more likely to support one candidate over the other. Evidence against my hypothesis would mean there is no meaningful relationship between race and vote choice, or a pattern where race does not significantly predict voting behavior after controlling for factors such as party identification.




```{r}
library(tidyverse)
isdata <- read_csv("~/Downloads/anes_timeseries_2024_csv_20250808/anes_timeseries_2024_csv_20250808.csv") 
```

